# Generated by Django 2.0.4 on 2018-07-23 05:46

import callisto_core.wizard_builder.model_helpers
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wizard_builder', '0050_remove_page_sites'),
    ]

    operations = [
        migrations.CreateModel(
            name='Date',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
            },
            bases=(callisto_core.wizard_builder.model_helpers.ProxyQuestion, 'wizard_builder.formquestion'),
        ),
        migrations.CreateModel(
            name='FileUpload',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
            },
            bases=(callisto_core.wizard_builder.model_helpers.ProxyQuestion, 'wizard_builder.formquestion'),
        ),
    ]
